var alphas = ["1", "2", "3", "4"];
console.log(alphas);
console.log(typeof alphas);
alphas.push('6');
console.log(alphas);
alphas.pop();
alphas.pop();
console.log(alphas);
var arr_names = new Array(3);
arr_names.push(1);
arr_names.push(2);
arr_names.push(3);
arr_names.push(4);
console.log('Arr', arr_names);
console.log('Arr', arr_names.indexOf(1));
console.log(typeof arr_names);
